[Service]
WorkingDirectory=/var/www/atg/atg-backend/current
EnvironmentFile=/var/www/atg/atg-backend/shared/.env
ExecStart=
ExecStart=/var/www/atg/atg-backend/current/.venv/bin/python -m celery -A myProject beat -l info --schedule=/var/www/atg/atg-backend/shared/celerybeat/celerybeat-schedule
