# Generated by Django 4.2.29 on 2026-03-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('trip_issue', 'Trip Complaint'), ('driver_issue', 'Driver Issue'), ('service_issue', 'Service Issue'), ('payment_issue', 'Payment Issue'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LostProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('luggage', 'Luggage'), ('bag', 'Bag'), ('wallet', 'Wallet'), ('phone', 'Phone'), ('keys', 'Keys'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('item_description', models.TextField(help_text='Detailed description of the lost item')),
                ('item_color', models.CharField(blank=True, help_text='Color of the item', max_length=50, null=True)),
                ('item_brand', models.CharField(blank=True, help_text='Brand/make of the item', max_length=100, null=True)),
                ('lost_location', models.CharField(blank=True, help_text='Where the item was lost (pickup/dropoff/vehicle)', max_length=255, null=True)),
                ('contact_preference', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('sms', 'SMS')], default='phone', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('found', 'Found'), ('returned', 'Returned'), ('not_found', 'Not Found'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the lost item', null=True, upload_to='lost_property/photos/')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('found_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_property', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_property_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lost Properties',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
