# Generated by Django 4.2.29 on 2026-03-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=20)),
                ('sort_code', models.CharField(max_length=10)),
                ('registered_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pco', models.FileField(upload_to='driver_docs/pco/')),
                ('dbs', models.FileField(upload_to='driver_docs/dbs/')),
                ('dvla', models.FileField(upload_to='driver_docs/dvla/')),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connect account ID', max_length=255, null=True)),
                ('driver_commission_percentage', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Custom commission percentage for this driver. If null, uses vehicle type rule or default.', max_digits=5, null=True)),
                ('bank_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.bankdetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_driver', to='drivers.basedriver')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_drivers', to='office.office')),
            ],
        ),
        migrations.CreateModel(
            name='NormalDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal_driver', to='drivers.basedriver')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal_driver', to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOnboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('home_postcode', models.CharField(max_length=255)),
                ('preferred_communication', models.CharField(choices=[('phone', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('years_experience', models.CharField(choices=[('less_than_1', 'Less than 1 year'), ('1_to_3', '1–3 years'), ('3_to_5', '3–5 years'), ('5_plus', '5+ years')], max_length=20)),
                ('previous_companies', models.JSONField(blank=True, default=list)),
                ('familiar_areas', models.JSONField(blank=True, default=list)),
                ('preferred_journey_types', models.JSONField(blank=True, default=list)),
                ('vehicle_ownership', models.CharField(choices=[('phv_owner', 'PHV Owner'), ('hiring_a_phv', 'Hiring a PHV'), ('do_not_have_a_phv', 'Do not have a PHV'), ('other', 'Other')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('5_seater_standard', '5-seater (Standard)'), ('7_seaters', '7 Seaters'), ('van_transporter', 'Van/Transporter'), ('other', 'Other')], max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ev', 'Electric Vehicle (EV)'), ('plug_in_hybrid', 'Plug-in Hybrid'), ('hybrid', 'Hybrid')], max_length=20)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('nights', 'Nights'), ('flexible', 'Flexible')], max_length=20)),
                ('notification_method', models.CharField(choices=[('app', 'Mobile App'), ('sms', 'SMS'), ('email', 'Email'), ('no_preference', 'No Preference')], max_length=20)),
                ('has_tfl_licence', models.BooleanField(default=False)),
                ('willing_dbs_check', models.BooleanField(default=False)),
                ('agrees_policies', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('step1_approved', 'Step 1 Approved - Upload Documents'), ('step1_rejected', 'Step 1 Rejected'), ('documents_uploaded', 'Documents Uploaded - Pending Final Review'), ('final_approved', 'Final Approved'), ('final_rejected', 'Final Rejected'), ('needs_modification', 'Needs Modification')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('files_need_modification', models.JSONField(blank=True, default=list, help_text="List of file names that need modification: ['pco', 'dbs', 'dvla', 'mot', 'phv']")),
                ('modification_confirmed', models.BooleanField(default=False, help_text='Whether driver has confirmed the file modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboarding_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_onboarding_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Onboarding Request',
                'verbose_name_plural': 'Driver Onboarding Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
