# Generated by Django 4.2.29 on 2026-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('price_breakdown', models.JSONField()),
                ('trip_data', models.JSONField()),
                ('passenger_id', models.IntegerField()),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['payment_intent_id'], name='payments_pe_payment_d0a2e9_idx'), models.Index(fields=['expires_at'], name='payments_pe_expires_dbd6b8_idx')],
            },
        ),
    ]
