# Generated by Django 4.2.29 on 2026-03-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEarningLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='drivers.basedriver')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('total_earnings', models.PositiveIntegerField(default=0)),
                ('successful_transfers', models.PositiveIntegerField(default=0)),
                ('failed_transfers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverRefundLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('refund_rule', models.CharField(choices=[('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_REFUND', 'No Refund')], max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='drivers.basedriver')),
                ('driver_earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='earnings.driverearningledger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_refunds', to='trips.trip')),
            ],
        ),
        migrations.AddField(
            model_name='driverearningledger',
            name='payout_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='earnings.payoutbatch'),
        ),
        migrations.AddField(
            model_name='driverearningledger',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_earning', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='CompanyRevenueLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_revenue', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRefundLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_refunds', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('driver_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled'), ('PAID', 'Paid')], default='SUBMITTED', max_length=20)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Always NULL in MVP - pay all available earnings', max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('note', models.TextField(blank=True, help_text="Driver's message/note")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text="Admin's review note/reason")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='drivers.basedriver')),
                ('payout_batch', models.ForeignKey(blank=True, help_text='Payout batch that processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='earnings.payoutbatch')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'status'], name='earnings_wi_driver__248212_idx'), models.Index(fields=['status', 'created_at'], name='earnings_wi_status_e14d0d_idx'), models.Index(fields=['payout_batch'], name='earnings_wi_payout__c992b7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'APPROVED'])), fields=('driver',), name='unique_driver_active_request'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['batch_id'], name='earnings_pa_batch_i_0b26ab_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutbatch',
            index=models.Index(fields=['status', 'created_at'], name='earnings_pa_status_9e5d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='driverrefundledger',
            index=models.Index(fields=['driver', 'trip'], name='earnings_dr_driver__00fe43_idx'),
        ),
        migrations.AddIndex(
            model_name='driverrefundledger',
            index=models.Index(fields=['stripe_idempotency_key'], name='earnings_dr_stripe__ae5e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='driverearningledger',
            index=models.Index(fields=['driver', 'status'], name='earnings_dr_driver__1d9cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='driverearningledger',
            index=models.Index(fields=['trip'], name='earnings_dr_trip_id_ebbbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='driverearningledger',
            index=models.Index(fields=['stripe_idempotency_key'], name='earnings_dr_stripe__1ad70d_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverearningledger',
            constraint=models.UniqueConstraint(fields=('trip',), name='unique_trip_earning'),
        ),
        migrations.AddConstraint(
            model_name='companyrevenueledger',
            constraint=models.UniqueConstraint(fields=('trip',), name='unique_trip_company_revenue'),
        ),
        migrations.AddIndex(
            model_name='companyrefundledger',
            index=models.Index(fields=['trip'], name='earnings_co_trip_id_6f3c75_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrefundledger',
            index=models.Index(fields=['stripe_idempotency_key'], name='earnings_co_stripe__acbcc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionrule',
            constraint=models.CheckConstraint(check=models.Q(('company_percentage__gte', 0), ('company_percentage__lte', 100)), name='valid_company_percentage'),
        ),
        migrations.AddConstraint(
            model_name='commissionrule',
            constraint=models.CheckConstraint(check=models.Q(('driver_percentage__gte', 0), ('driver_percentage__lte', 100)), name='valid_driver_percentage'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionrule',
            unique_together={('vehicle_type', 'is_active')},
        ),
    ]
