import { customerText } from "@/lib/customer-text";
const arabic: Record<string, string> = {
  "Back": "رجوع",
  "Continue": "متابعة",
  "Passenger Details": "بيانات الراكب",
  "Full Name": "الاسم الكامل",
  "Email": "البريد الإلكتروني",
  "Country Code": "رمز الدولة",
  "Mobile Number": "رقم الهاتف المحمول",
  "Passenger name, email, country code, and mobile number are required.": "يرجى إدخال اسم الراكب والبريد الإلكتروني ورمز الدولة ورقم الهاتف المحمول.",
  "+44 United Kingdom": "+44 المملكة المتحدة",
  "+1 United States": "+1 الولايات المتحدة",
  "+971 United Arab Emirates": "+971 الإمارات العربية المتحدة",
  "+966 Saudi Arabia": "+966 المملكة العربية السعودية",
  "+974 Qatar": "+974 قطر",
  "+965 Kuwait": "+965 الكويت",
  "+973 Bahrain": "+973 البحرين",
  "+968 Oman": "+968 عُمان",
  "Travelling with Children or Infants?": "هل تسافر مع أطفال أو رُضّع؟",
  "UK guidance generally requires children to use an appropriate child restraint based on age, height and weight. Please confirm how child or infant seats will be handled for this booking.": "تتطلب الإرشادات البريطانية عمومًا استخدام مقعد أمان مناسب للأطفال بحسب العمر والطول والوزن. يرجى تحديد ترتيبات مقاعد الأطفال أو الرُضّع لهذا الحجز.",
  "Infant Seat Requirement": "متطلبات مقعد الرضيع",
  "Child Seat Requirement": "متطلبات مقعد الطفل",
  "Read UK guidance": "اطّلع على الإرشادات البريطانية",
  "• Infants (0-3 years): Should travel in a suitable infant or child seat.": "• الرُضّع (0–3 سنوات): ينبغي استخدام مقعد مناسب للرُضّع أو الأطفال.",
  "• Children (4-11 years): Should normally use a suitable child seat until 12 years old or 135cm tall, whichever comes first.": "• الأطفال (4–11 سنة): ينبغي عادةً استخدام مقعد طفل مناسب حتى بلوغ 12 عامًا أو طول 135 سم، أيهما أسبق.",
  "• Children aged 12+ or taller than 135cm: Must use an adult seat belt.": "• الأطفال بعمر 12 عامًا فأكثر أو بطول يتجاوز 135 سم: يجب استخدام حزام أمان للكبار.",
  "Please select the required child or infant seat option before continuing.": "يرجى اختيار ترتيبات مقعد الطفل أو الرضيع المطلوبة قبل المتابعة.",
  "I will provide my own infant seats": "سأوفّر مقاعد الرُضّع بنفسي",
  "I would like ACT to provide infant seats": "أرغب في أن توفّر ACT مقاعد الرُضّع",
  "I understand ACT may not have infant seats available and wish to continue": "أفهم أن مقاعد الرُضّع قد لا تتوفر لدى ACT وأرغب في المتابعة",
  "I will provide my own child seats": "سأوفّر مقاعد الأطفال بنفسي",
  "I would like ACT to provide child seats": "أرغب في أن توفّر ACT مقاعد الأطفال",
  "I understand ACT may not have child seats available and wish to continue": "أفهم أن مقاعد الأطفال قد لا تتوفر لدى ACT وأرغب في المتابعة",
  "Flight Details": "تفاصيل الرحلة الجوية",
  "Flight Type": "نوع الرحلة الجوية",
  "Arrival": "وصول",
  "Departure": "مغادرة",
  "Arrival is selected because your journey starts at an airport.": "تم اختيار الوصول لأن رحلتك تبدأ من المطار.",
  "Departure is selected because your journey ends at an airport.": "تم اختيار المغادرة لأن رحلتك تنتهي في المطار.",
  "Flight type is optional. Select one if you would like to add flight timing details.": "نوع الرحلة الجوية اختياري. اختر النوع إذا رغبت في إضافة تفاصيل مواعيد الطيران.",
  "Please enter the scheduled flight landing/departure time.": "يرجى إدخال موعد الوصول أو المغادرة المقرر للرحلة الجوية.",
  "For arrivals, your pickup time should allow enough time for immigration, baggage collection, and meeting your driver.": "لرحلات الوصول، يرجى اختيار وقت استلام يتيح وقتًا كافيًا لإجراءات الجوازات واستلام الأمتعة ولقاء السائق.",
  "For departures, allow enough travel and airport check-in time before your scheduled flight.": "لرحلات المغادرة، يرجى إتاحة وقت كافٍ للوصول إلى المطار وإجراءات تسجيل السفر قبل موعد الرحلة.",
  "Flight Number": "رقم الرحلة الجوية",
  "Airline": "شركة الطيران",
  "Landing Time": "وقت الوصول",
  "Departure Time": "وقت المغادرة",
  "Select landing time": "اختر وقت الوصول",
  "Select departure time": "اختر وقت المغادرة",
  "Go back and change pickup time": "ارجع لتعديل وقت الاستلام",
  "Pick-up Sign Name": "الاسم على لافتة الاستقبال",
  "Departure Time is required for departure flights.": "يرجى إدخال وقت المغادرة لرحلات المغادرة.",
  "Landing Time is required for arrival flights.": "يرجى إدخال وقت الوصول لرحلات الوصول.",
  "Skip — Not applicable for this journey": "تخطٍّ — لا ينطبق على هذه الرحلة",
  "Adults": "البالغون",
  "Children (4-11)": "الأطفال (4–11 سنة)",
  "Infants (0-3)": "الرُضّع (0–3 سنوات)",
  "Luggage": "الأمتعة",
  "Adults must be at least 1.": "يجب أن يكون عدد البالغين واحدًا على الأقل.",
  "Total passengers": "إجمالي الركاب",
  "Infant seat option selected": "خيار مقعد الرضيع المحدد",
  "Child seat option selected": "خيار مقعد الطفل المحدد",
  "Not provided": "غير محدد",
  "We could not calculate this journey. Please check the pickup and drop-off addresses and try again.": "تعذّر حساب هذه الرحلة. يرجى التحقق من عنوانَي الاستلام والوصول والمحاولة مجددًا."
};

// Display text only: never translate stored booking values or customer input.
export const bookingText = (locale: string, text: string): string =>
  locale === "ar" ? arabic[text] ?? text : customerText(locale, text);
