# Generated by Django 4.2.29 on 2026-03-14 12:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        ('passengers', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Airport Name (English)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Airport Name (Arabic)')),
                ('pickup_vat', models.FloatField()),
                ('dropoff_vat', models.FloatField()),
                ('detection_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Polygon area for automatic airport detection. Pickup/dropoff within this area will be detected as airport trips.', null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this airport is active for automatic detection')),
                ('vehicle_specific_fees', models.JSONField(blank=True, default=dict, help_text="Optional: {vehicle_type_id: {'pickup_fee': X, 'dropoff_fee': Y}}")),
            ],
        ),
        migrations.CreateModel(
            name='GuestDriverCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Car brand (e.g., Toyota, Mercedes)', max_length=100)),
                ('model', models.CharField(help_text='Car model (e.g., Camry, E-Class)', max_length=100)),
                ('color', models.CharField(help_text='Car color (e.g., Black, White, Silver)', max_length=50)),
                ('registration_number', models.CharField(db_index=True, help_text='Vehicle registration/license plate number', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of manufacture (optional)', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text="Optional notes about the car (e.g., 'Clean interior', 'GPS installed')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_str', models.CharField(blank=True, max_length=500, null=True)),
                ('pickup_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_str', models.CharField(blank=True, max_length=500, null=True)),
                ('dropoff_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('expected_trip_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated trip duration in minutes', null=True)),
                ('distance_miles', models.FloatField(blank=True, help_text='Estimated distance in miles', null=True)),
                ('trip_date', models.DateField()),
                ('trip_time', models.TimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passengers_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('driver_on_the_way', 'Driver on the way'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airport_direction', models.CharField(choices=[('from', 'From Airport'), ('to', 'To Airport')], help_text='Indicates if the airport is for pickup or dropoff', max_length=5, null=True)),
                ('large_suitcase', models.PositiveIntegerField(default=0)),
                ('small_suitcase', models.PositiveIntegerField(default=0)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('base_trip_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('airport_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_guest_driver', models.BooleanField(default=False, help_text='True if assigned to external/guest driver')),
                ('guest_driver_name', models.CharField(blank=True, help_text='Name of guest driver', max_length=255, null=True)),
                ('guest_driver_phone', models.CharField(blank=True, help_text='Phone number of guest driver', max_length=20, null=True)),
                ('guest_driver_company', models.CharField(blank=True, help_text='Company name (e.g., Uber, Bolt)', max_length=255, null=True)),
                ('cancelled_by_driver', models.BooleanField(default=False, help_text='True if driver cancelled this trip')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the trip was cancelled', null=True)),
                ('airport', models.ForeignKey(help_text='If trip starts or ends at an airport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.airport')),
                ('base_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.basedriver')),
                ('cancelled_by_driver_id', models.ForeignKey(blank=True, help_text='Driver who cancelled this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_trips', to='drivers.basedriver')),
                ('car_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicle.vehicletype')),
                ('guest_driver_car', models.ForeignKey(blank=True, help_text='Car information for guest driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.guestdrivercar')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='office.office')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='passengers.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_lat', models.FloatField()),
                ('point_lng', models.FloatField()),
                ('point_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('point_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('point_str', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_points', to='trips.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='guestdrivercar',
            index=models.Index(fields=['registration_number'], name='trips_guest_registr_e27329_idx'),
        ),
    ]
