# Generated by Django 4.2.29 on 2026-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='booking_confirmation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='trips/booking_confirmations/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancellation_confirmation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='trips/cancellation_confirmations/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='Stripe Invoice id (in_...) when the trip was paid via an invoice', max_length=255, null=True),
        ),
    ]
