# Generated by Django 4.2.29 on 2026-03-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('TERMS_AND_CONDITIONS', 'Terms and Conditions'), ('FAQ', 'FAQ'), ('PRIVACY_POLICY', 'Privacy Policy'), ('DRIVER_GUIDELINES', 'Driver Guidelines'), ('PASSENGER_GUIDELINES', 'Passenger Guidelines'), ('OTHER', 'Other')], help_text='Type of instruction file', max_length=50, unique=True)),
                ('title', models.CharField(help_text="Title of the file (e.g., 'Terms and Conditions', 'FAQ')", max_length=255)),
                ('file', models.FileField(help_text='The instruction file (PDF, DOC, DOCX, etc.)', upload_to='instruction_files/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the file', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this file is currently active and should be shown to users')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of the file (incremented on updates)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instruction_files', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_instruction_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['file_type', 'is_active'], name='admin_panel_file_ty_70b086_idx'), models.Index(fields=['is_active'], name='admin_panel_is_acti_25a59e_idx')],
            },
        ),
    ]
